-- V8__question_bank.sql

CREATE TABLE question_bank (
    id BIGSERIAL PRIMARY KEY,
    role VARCHAR(255) NOT NULL,
    difficulty VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    question_text TEXT NOT NULL,
    expected_answer TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO question_bank (role, difficulty, category, question_text, expected_answer) VALUES
('PYTHON_DEVELOPER', 'EASY', 'project', 'What are the trade-offs when using Decorators?', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'project', 'What are the best practices for implementing Python Fundamentals?', 'An ideal answer should discuss Python Fundamentals in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'behavioral', 'What are the trade-offs when using FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'technical', 'What is the underlying mechanism behind Flask?', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'project', 'Explain how Decorators improves system scalability.', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'technical', 'Explain the concept of Flask and how it applies to modern development.', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'technical', 'Explain the concept of Decorators and how it applies to modern development.', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'behavioral', 'What are the trade-offs when using Flask?', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'behavioral', 'What are the best practices for implementing Flask?', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'EASY', 'technical', 'What are the trade-offs when using FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'Explain how Decorators improves system scalability.', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'Explain the concept of Django and how it applies to modern development.', 'An ideal answer should discuss Django in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'project', 'How does Python Fundamentals differ from alternative approaches?', 'An ideal answer should discuss Python Fundamentals in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on Python Fundamentals?', 'An ideal answer should discuss Python Fundamentals in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'What are the best practices for implementing FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'Can you provide an example of when NOT to use Decorators?', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'behavioral', 'Describe a time you encountered a challenging bug related to FastAPI.', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'behavioral', 'What are the trade-offs when using Decorators?', 'An ideal answer should discuss Decorators in depth.'),
('PYTHON_DEVELOPER', 'MEDIUM', 'technical', 'Can you provide an example of when NOT to use FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'behavioral', 'Discuss the security implications of FastAPI.', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to Python Fundamentals.', 'An ideal answer should discuss Python Fundamentals in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'behavioral', 'What are the trade-offs when using FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'behavioral', 'Discuss the security implications of Django.', 'An ideal answer should discuss Django in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'technical', 'How does Flask differ from alternative approaches?', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'project', 'What are the trade-offs when using Python Fundamentals?', 'An ideal answer should discuss Python Fundamentals in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'behavioral', 'What are the best practices for implementing Flask?', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'behavioral', 'Explain the concept of Django and how it applies to modern development.', 'An ideal answer should discuss Django in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'project', 'Describe a time you encountered a challenging bug related to Flask.', 'An ideal answer should discuss Flask in depth.'),
('PYTHON_DEVELOPER', 'HARD', 'technical', 'How would you optimize an application that relies heavily on FastAPI?', 'An ideal answer should discuss FastAPI in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'Discuss the security implications of Statistics.', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'EASY', 'project', 'What are the trade-offs when using Statistics?', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'Can you provide an example of when NOT to use Data Visualization?', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'EASY', 'technical', 'Explain the concept of Power BI and how it applies to modern development.', 'An ideal answer should discuss Power BI in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'How would you optimize an application that relies heavily on Statistics?', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'How does Power BI differ from alternative approaches?', 'An ideal answer should discuss Power BI in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'Discuss the security implications of Data Visualization.', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'EASY', 'technical', 'How does Statistics differ from alternative approaches?', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'EASY', 'behavioral', 'What are the trade-offs when using SQL?', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'EASY', 'project', 'What is the underlying mechanism behind SQL?', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'MEDIUM', 'technical', 'Discuss the security implications of Data Visualization.', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on Power BI?', 'An ideal answer should discuss Power BI in depth.'),
('DATA_ANALYST', 'MEDIUM', 'project', 'What is the underlying mechanism behind SQL?', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'MEDIUM', 'project', 'Discuss the security implications of SQL.', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'MEDIUM', 'behavioral', 'Explain how Statistics improves system scalability.', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'MEDIUM', 'behavioral', 'Explain how Data Visualization improves system scalability.', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'MEDIUM', 'technical', 'Explain how Statistics improves system scalability.', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'MEDIUM', 'behavioral', 'Explain the concept of Statistics and how it applies to modern development.', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'MEDIUM', 'technical', 'Describe a time you encountered a challenging bug related to Power BI.', 'An ideal answer should discuss Power BI in depth.'),
('DATA_ANALYST', 'MEDIUM', 'project', 'What is the underlying mechanism behind Data Visualization?', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'HARD', 'technical', 'What are the trade-offs when using Power BI?', 'An ideal answer should discuss Power BI in depth.'),
('DATA_ANALYST', 'HARD', 'behavioral', 'Discuss the security implications of Python.', 'An ideal answer should discuss Python in depth.'),
('DATA_ANALYST', 'HARD', 'technical', 'What are the trade-offs when using SQL?', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'HARD', 'behavioral', 'What is the underlying mechanism behind Statistics?', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'HARD', 'project', 'Discuss the security implications of Python.', 'An ideal answer should discuss Python in depth.'),
('DATA_ANALYST', 'HARD', 'technical', 'Explain how SQL improves system scalability.', 'An ideal answer should discuss SQL in depth.'),
('DATA_ANALYST', 'HARD', 'technical', 'Explain the concept of Statistics and how it applies to modern development.', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'HARD', 'behavioral', 'Explain how Data Visualization improves system scalability.', 'An ideal answer should discuss Data Visualization in depth.'),
('DATA_ANALYST', 'HARD', 'technical', 'What is the underlying mechanism behind Statistics?', 'An ideal answer should discuss Statistics in depth.'),
('DATA_ANALYST', 'HARD', 'behavioral', 'Explain how Power BI improves system scalability.', 'An ideal answer should discuss Power BI in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'technical', 'Explain the concept of Databases and how it applies to modern development.', 'An ideal answer should discuss Databases in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'behavioral', 'What are the trade-offs when using Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'technical', 'What are the trade-offs when using Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'technical', 'Explain how Authentication improves system scalability.', 'An ideal answer should discuss Authentication in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'technical', 'Explain the concept of React and how it applies to modern development.', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'technical', 'How does Deployment differ from alternative approaches?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'behavioral', 'How does Deployment differ from alternative approaches?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'project', 'Can you provide an example of when NOT to use Authentication?', 'An ideal answer should discuss Authentication in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'behavioral', 'Discuss the security implications of Spring Boot.', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'EASY', 'behavioral', 'Explain how Deployment improves system scalability.', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'behavioral', 'What is the underlying mechanism behind Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'behavioral', 'What are the trade-offs when using Authentication?', 'An ideal answer should discuss Authentication in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'project', 'Explain the concept of Spring Boot and how it applies to modern development.', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'project', 'How would you optimize an application that relies heavily on Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'technical', 'What are the best practices for implementing Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'behavioral', 'What is the underlying mechanism behind React?', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'technical', 'How does React differ from alternative approaches?', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'technical', 'What is the underlying mechanism behind React?', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'MEDIUM', 'technical', 'Explain the concept of Spring Boot and how it applies to modern development.', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'project', 'Can you provide an example of when NOT to use Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'project', 'How would you optimize an application that relies heavily on Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'technical', 'Explain the concept of React and how it applies to modern development.', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'project', 'What is the underlying mechanism behind Databases?', 'An ideal answer should discuss Databases in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'behavioral', 'What are the best practices for implementing React?', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'behavioral', 'Discuss the security implications of React.', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'project', 'How would you optimize an application that relies heavily on Deployment?', 'An ideal answer should discuss Deployment in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'behavioral', 'Can you provide an example of when NOT to use React?', 'An ideal answer should discuss React in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to Databases.', 'An ideal answer should discuss Databases in depth.'),
('FULL_STACK_DEVELOPER', 'HARD', 'technical', 'How would you optimize an application that relies heavily on React?', 'An ideal answer should discuss React in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'technical', 'Discuss the security implications of Hibernate.', 'An ideal answer should discuss Hibernate in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'project', 'How does Core Java differ from alternative approaches?', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'technical', 'How does Microservices differ from alternative approaches?', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'behavioral', 'Explain the concept of Microservices and how it applies to modern development.', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'technical', 'Discuss the security implications of REST APIs.', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'project', 'How would you optimize an application that relies heavily on REST APIs?', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'technical', 'Can you provide an example of when NOT to use REST APIs?', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'technical', 'Explain how Spring Boot improves system scalability.', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'project', 'How would you optimize an application that relies heavily on Microservices?', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'EASY', 'behavioral', 'Describe a time you encountered a challenging bug related to REST APIs.', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'project', 'Can you provide an example of when NOT to use Core Java?', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'project', 'What are the trade-offs when using Microservices?', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'technical', 'How does Spring Boot differ from alternative approaches?', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'project', 'Explain how Microservices improves system scalability.', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'technical', 'Can you provide an example of when NOT to use Core Java?', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'project', 'Explain the concept of Spring Boot and how it applies to modern development.', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'project', 'What is the underlying mechanism behind REST APIs?', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'technical', 'Can you provide an example of when NOT to use Core Java?', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'MEDIUM', 'behavioral', 'Discuss the security implications of Spring Boot.', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'behavioral', 'What is the underlying mechanism behind Core Java?', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'behavioral', 'What is the underlying mechanism behind Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'behavioral', 'Explain the concept of Microservices and how it applies to modern development.', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to Core Java.', 'An ideal answer should discuss Core Java in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'technical', 'Can you provide an example of when NOT to use REST APIs?', 'An ideal answer should discuss REST APIs in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'technical', 'Explain how Hibernate improves system scalability.', 'An ideal answer should discuss Hibernate in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'behavioral', 'How would you optimize an application that relies heavily on Microservices?', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'technical', 'Discuss the security implications of Microservices.', 'An ideal answer should discuss Microservices in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'behavioral', 'What are the best practices for implementing Spring Boot?', 'An ideal answer should discuss Spring Boot in depth.'),
('JAVA_BACKEND_DEVELOPER', 'HARD', 'technical', 'Discuss the security implications of Core Java.', 'An ideal answer should discuss Core Java in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'technical', 'What are the trade-offs when using HTML?', 'An ideal answer should discuss HTML in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'project', 'Explain the concept of JavaScript and how it applies to modern development.', 'An ideal answer should discuss JavaScript in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'project', 'Discuss the security implications of State Management.', 'An ideal answer should discuss State Management in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'project', 'How does React differ from alternative approaches?', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'technical', 'What are the trade-offs when using State Management?', 'An ideal answer should discuss State Management in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'project', 'What are the trade-offs when using State Management?', 'An ideal answer should discuss State Management in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'technical', 'Describe a time you encountered a challenging bug related to React.', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'project', 'Can you provide an example of when NOT to use CSS?', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'technical', 'How does CSS differ from alternative approaches?', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'EASY', 'behavioral', 'How would you optimize an application that relies heavily on HTML?', 'An ideal answer should discuss HTML in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'project', 'What are the trade-offs when using HTML?', 'An ideal answer should discuss HTML in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'behavioral', 'Can you provide an example of when NOT to use State Management?', 'An ideal answer should discuss State Management in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'behavioral', 'Explain the concept of React and how it applies to modern development.', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on State Management?', 'An ideal answer should discuss State Management in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'project', 'Explain the concept of JavaScript and how it applies to modern development.', 'An ideal answer should discuss JavaScript in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'project', 'Explain the concept of CSS and how it applies to modern development.', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'project', 'Discuss the security implications of HTML.', 'An ideal answer should discuss HTML in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'behavioral', 'Describe a time you encountered a challenging bug related to React.', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'project', 'Can you provide an example of when NOT to use React?', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'MEDIUM', 'technical', 'How would you optimize an application that relies heavily on CSS?', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'behavioral', 'What is the underlying mechanism behind CSS?', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'technical', 'Explain the concept of React and how it applies to modern development.', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'technical', 'Explain the concept of JavaScript and how it applies to modern development.', 'An ideal answer should discuss JavaScript in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'technical', 'What are the trade-offs when using React?', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'behavioral', 'What is the underlying mechanism behind CSS?', 'An ideal answer should discuss CSS in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'behavioral', 'How does HTML differ from alternative approaches?', 'An ideal answer should discuss HTML in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'project', 'Can you provide an example of when NOT to use JavaScript?', 'An ideal answer should discuss JavaScript in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'behavioral', 'Explain the concept of React and how it applies to modern development.', 'An ideal answer should discuss React in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'technical', 'What are the best practices for implementing JavaScript?', 'An ideal answer should discuss JavaScript in depth.'),
('FRONTEND_DEVELOPER', 'HARD', 'project', 'Explain how State Management improves system scalability.', 'An ideal answer should discuss State Management in depth.'),
('SYSTEM_DESIGN', 'EASY', 'project', 'What is the underlying mechanism behind Database Design?', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'EASY', 'behavioral', 'How would you optimize an application that relies heavily on Database Design?', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'EASY', 'technical', 'Explain the concept of Database Design and how it applies to modern development.', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'EASY', 'technical', 'What are the best practices for implementing Microservices?', 'An ideal answer should discuss Microservices in depth.'),
('SYSTEM_DESIGN', 'EASY', 'project', 'Describe a time you encountered a challenging bug related to Caching.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'EASY', 'behavioral', 'Discuss the security implications of Microservices.', 'An ideal answer should discuss Microservices in depth.'),
('SYSTEM_DESIGN', 'EASY', 'behavioral', 'How does Microservices differ from alternative approaches?', 'An ideal answer should discuss Microservices in depth.'),
('SYSTEM_DESIGN', 'EASY', 'technical', 'Explain the concept of Caching and how it applies to modern development.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'EASY', 'project', 'Describe a time you encountered a challenging bug related to Caching.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'EASY', 'technical', 'Explain how Scalability improves system scalability.', 'An ideal answer should discuss Scalability in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'project', 'How does Database Design differ from alternative approaches?', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'behavioral', 'What are the best practices for implementing Scalability?', 'An ideal answer should discuss Scalability in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'behavioral', 'What is the underlying mechanism behind Load Balancing?', 'An ideal answer should discuss Load Balancing in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'behavioral', 'How would you optimize an application that relies heavily on Database Design?', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'project', 'Explain the concept of Database Design and how it applies to modern development.', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'technical', 'Explain how Caching improves system scalability.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'technical', 'What are the trade-offs when using Caching?', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'behavioral', 'How does Caching differ from alternative approaches?', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'technical', 'Describe a time you encountered a challenging bug related to Caching.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'MEDIUM', 'behavioral', 'Can you provide an example of when NOT to use Load Balancing?', 'An ideal answer should discuss Load Balancing in depth.'),
('SYSTEM_DESIGN', 'HARD', 'project', 'What is the underlying mechanism behind Database Design?', 'An ideal answer should discuss Database Design in depth.'),
('SYSTEM_DESIGN', 'HARD', 'behavioral', 'How does Caching differ from alternative approaches?', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'HARD', 'project', 'What are the trade-offs when using Caching?', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'HARD', 'behavioral', 'Explain how Scalability improves system scalability.', 'An ideal answer should discuss Scalability in depth.'),
('SYSTEM_DESIGN', 'HARD', 'behavioral', 'Explain how Caching improves system scalability.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'HARD', 'project', 'Explain the concept of Caching and how it applies to modern development.', 'An ideal answer should discuss Caching in depth.'),
('SYSTEM_DESIGN', 'HARD', 'project', 'How would you optimize an application that relies heavily on Scalability?', 'An ideal answer should discuss Scalability in depth.'),
('SYSTEM_DESIGN', 'HARD', 'technical', 'What are the trade-offs when using Scalability?', 'An ideal answer should discuss Scalability in depth.'),
('SYSTEM_DESIGN', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to Load Balancing.', 'An ideal answer should discuss Load Balancing in depth.'),
('SYSTEM_DESIGN', 'HARD', 'behavioral', 'Describe a time you encountered a challenging bug related to Microservices.', 'An ideal answer should discuss Microservices in depth.'),
('AI_ML_ENGINEER', 'EASY', 'technical', 'What are the trade-offs when using Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'technical', 'What are the trade-offs when using PyTorch?', 'An ideal answer should discuss PyTorch in depth.'),
('AI_ML_ENGINEER', 'EASY', 'technical', 'What are the trade-offs when using Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'technical', 'What is the underlying mechanism behind Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'behavioral', 'What is the underlying mechanism behind NLP?', 'An ideal answer should discuss NLP in depth.'),
('AI_ML_ENGINEER', 'EASY', 'technical', 'Explain how Deep Learning improves system scalability.', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'project', 'How would you optimize an application that relies heavily on Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'behavioral', 'Explain how Machine Learning improves system scalability.', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'EASY', 'project', 'What are the trade-offs when using TensorFlow?', 'An ideal answer should discuss TensorFlow in depth.'),
('AI_ML_ENGINEER', 'EASY', 'project', 'Describe a time you encountered a challenging bug related to TensorFlow.', 'An ideal answer should discuss TensorFlow in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'What is the underlying mechanism behind PyTorch?', 'An ideal answer should discuss PyTorch in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'What are the trade-offs when using Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'behavioral', 'What is the underlying mechanism behind PyTorch?', 'An ideal answer should discuss PyTorch in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'What are the best practices for implementing Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'Discuss the security implications of PyTorch.', 'An ideal answer should discuss PyTorch in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'Explain how Deep Learning improves system scalability.', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'project', 'Can you provide an example of when NOT to use Deep Learning?', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'technical', 'What is the underlying mechanism behind Deep Learning?', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'technical', 'What are the best practices for implementing NLP?', 'An ideal answer should discuss NLP in depth.'),
('AI_ML_ENGINEER', 'MEDIUM', 'technical', 'What are the best practices for implementing Deep Learning?', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'project', 'What are the best practices for implementing Deep Learning?', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'project', 'Explain how Machine Learning improves system scalability.', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'technical', 'How does Machine Learning differ from alternative approaches?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'technical', 'Discuss the security implications of PyTorch.', 'An ideal answer should discuss PyTorch in depth.'),
('AI_ML_ENGINEER', 'HARD', 'behavioral', 'Describe a time you encountered a challenging bug related to NLP.', 'An ideal answer should discuss NLP in depth.'),
('AI_ML_ENGINEER', 'HARD', 'technical', 'What are the trade-offs when using Deep Learning?', 'An ideal answer should discuss Deep Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to TensorFlow.', 'An ideal answer should discuss TensorFlow in depth.'),
('AI_ML_ENGINEER', 'HARD', 'project', 'Describe a time you encountered a challenging bug related to NLP.', 'An ideal answer should discuss NLP in depth.'),
('AI_ML_ENGINEER', 'HARD', 'behavioral', 'What are the trade-offs when using Machine Learning?', 'An ideal answer should discuss Machine Learning in depth.'),
('AI_ML_ENGINEER', 'HARD', 'project', 'Discuss the security implications of TensorFlow.', 'An ideal answer should discuss TensorFlow in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'What are the best practices for implementing Linux?', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'What are the best practices for implementing Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'What are the trade-offs when using Kubernetes?', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'technical', 'Explain how AWS improves system scalability.', 'An ideal answer should discuss AWS in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'Discuss the security implications of Kubernetes.', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'technical', 'Explain the concept of Kubernetes and how it applies to modern development.', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'behavioral', 'How does Docker differ from alternative approaches?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'Explain the concept of Linux and how it applies to modern development.', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'What are the trade-offs when using Linux?', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'EASY', 'project', 'How would you optimize an application that relies heavily on Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'technical', 'Explain the concept of Kubernetes and how it applies to modern development.', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'technical', 'What is the underlying mechanism behind AWS?', 'An ideal answer should discuss AWS in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'technical', 'Discuss the security implications of Linux.', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'technical', 'Discuss the security implications of Kubernetes.', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'Explain how Linux improves system scalability.', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'Discuss the security implications of CI/CD.', 'An ideal answer should discuss CI/CD in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'What are the best practices for implementing CI/CD?', 'An ideal answer should discuss CI/CD in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'Explain the concept of CI/CD and how it applies to modern development.', 'An ideal answer should discuss CI/CD in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'How does CI/CD differ from alternative approaches?', 'An ideal answer should discuss CI/CD in depth.'),
('DEVOPS_ENGINEER', 'MEDIUM', 'behavioral', 'What is the underlying mechanism behind Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'project', 'Can you provide an example of when NOT to use CI/CD?', 'An ideal answer should discuss CI/CD in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'technical', 'Can you provide an example of when NOT to use AWS?', 'An ideal answer should discuss AWS in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'behavioral', 'Can you provide an example of when NOT to use Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'project', 'Discuss the security implications of AWS.', 'An ideal answer should discuss AWS in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'technical', 'Can you provide an example of when NOT to use Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'technical', 'What are the trade-offs when using Kubernetes?', 'An ideal answer should discuss Kubernetes in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'technical', 'How does Linux differ from alternative approaches?', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'technical', 'What is the underlying mechanism behind Docker?', 'An ideal answer should discuss Docker in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'project', 'What are the best practices for implementing Linux?', 'An ideal answer should discuss Linux in depth.'),
('DEVOPS_ENGINEER', 'HARD', 'project', 'Explain how Docker improves system scalability.', 'An ideal answer should discuss Docker in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'How does Data Structures differ from alternative approaches?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'technical', 'How does Networking differ from alternative approaches?', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'Explain the concept of Operating Systems and how it applies to modern development.', 'An ideal answer should discuss Operating Systems in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'Explain the concept of Networking and how it applies to modern development.', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'How does DBMS differ from alternative approaches?', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'technical', 'How would you optimize an application that relies heavily on OOP?', 'An ideal answer should discuss OOP in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'Describe a time you encountered a challenging bug related to Data Structures.', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'behavioral', 'Discuss the security implications of OOP.', 'An ideal answer should discuss OOP in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'technical', 'Describe a time you encountered a challenging bug related to Data Structures.', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'EASY', 'technical', 'Discuss the security implications of DBMS.', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Can you provide an example of when NOT to use DBMS?', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Explain how Networking improves system scalability.', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'behavioral', 'Explain how Networking improves system scalability.', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Describe a time you encountered a challenging bug related to Operating Systems.', 'An ideal answer should discuss Operating Systems in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Explain how Data Structures improves system scalability.', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'What are the best practices for implementing Data Structures?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'behavioral', 'Explain the concept of OOP and how it applies to modern development.', 'An ideal answer should discuss OOP in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Explain how DBMS improves system scalability.', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'project', 'Describe a time you encountered a challenging bug related to DBMS.', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'MEDIUM', 'technical', 'How does Data Structures differ from alternative approaches?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'technical', 'What are the trade-offs when using DBMS?', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'technical', 'Describe a time you encountered a challenging bug related to Networking.', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'project', 'Explain how OOP improves system scalability.', 'An ideal answer should discuss OOP in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'project', 'Can you provide an example of when NOT to use Data Structures?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'project', 'Explain how Networking improves system scalability.', 'An ideal answer should discuss Networking in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'behavioral', 'How would you optimize an application that relies heavily on Data Structures?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'project', 'How would you optimize an application that relies heavily on Data Structures?', 'An ideal answer should discuss Data Structures in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'project', 'What are the trade-offs when using DBMS?', 'An ideal answer should discuss DBMS in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'behavioral', 'What are the best practices for implementing OOP?', 'An ideal answer should discuss OOP in depth.'),
('CS_FUNDAMENTALS', 'HARD', 'technical', 'What is the underlying mechanism behind Networking?', 'An ideal answer should discuss Networking in depth.');
